services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "M@ster.01"
      ACCEPT_EULA: "Y"
    ports:
      - "14330:1433"
    volumes:
      - sql_data:/var/opt/mssql

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  backend-migrator:
    build:
      context: .
      dockerfile: src/backend/Dockerfile.migrator
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    profiles:
      - migrate
    depends_on:
      - db

  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./src/frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:5001/api
    depends_on:
      - backend

volumes:
  sql_data:
