services:
  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
      target: runtime  # Production runtime stage
    restart: unless-stopped
    
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
      target: production  # Production stage
    ports:
      - "5002:80"  # Nginx production server
    restart: unless-stopped
