services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: evrendev-db
    environment:
      SA_PASSWORD: "M@ster.01"
      ACCEPT_EULA: "Y"
    ports:
      - "14330:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - evrendev-network

  redis:
    container_name: evrendev-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - evrendev-network

  backend-migrator:
    container_name: evrendev-migrator
    image: evrendev-migrator
    build:
      context: .
      dockerfile: src/backend/Dockerfile.migrator
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - Logging__LogLevel__Default=Debug
      - Logging__LogLevel__Microsoft=Debug
      - Logging__LogLevel__Microsoft.Hosting.Lifetime=Debug
    profiles:
      - migrate
    depends_on:
      - db
    networks:
      - evrendev-network

  backend:
    container_name: evrendev-backend
    image: evrendev-backend
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    # ports:
    #   - "6001:6001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - Logging__LogLevel__Default=Debug
      - Logging__LogLevel__Microsoft=Debug
      - Logging__LogLevel__Microsoft.Hosting.Lifetime=Debug
    restart: unless-stopped
    depends_on:
      - db
      - redis
    networks:
      - evrendev-network

  frontend:
    container_name: evrendev-frontend
    image: evrendev-frontend
    build:
      context: ./src/frontend
    # ports:
    #   - "6002:6002"
    environment:
      - VITE_API_URL=https://donation.help-dunya.com:5001/api

    depends_on:
      - backend
    networks:
      - evrendev-network

volumes:
  sql_data:

networks:
  evrendev-network:
    name: evrendev-network
    driver: bridge
