import {
  mdiClose,
  mdiHome,
  mdiEyeOff,
  mdiEye,
  mdiHeart,
  mdiRefresh,
  mdiLogin,
  mdiFish,
  mdiKeyboardReturn,
  mdiCheck,
  mdiCheckCircle,
  mdiAlertCircle,
  mdiAlert,
  mdiInformation,
  mdiFilterCheck,
  mdiMagnifyExpand,
  mdiPencil,
  mdiThumbUp,
  mdiThumbDown,
  mdiTrashCan,
  mdiArrowUpBoldCircle,
  mdiContentSave,
  mdiShieldAccount,
  mdiShieldLockOpen,
  mdiInformationBox
} from "@mdi/js";

export const icons = {
  close: mdiClose,
  home: mdiHome,
  eyeOff: mdiEyeOff,
  eye: mdiEye,
  heart: mdiHeart,
  refresh: mdiRefresh,
  login: mdiLogin,
  fish: mdiFish,
  return: mdiKeyboardReturn,
  check: mdiCheck,
  checkCircle: mdiCheckCircle,
  alertCircle: mdiAlertCircle,
  alert: mdiAlert,
  information: mdiInformation,
  filterCheck: mdiFilterCheck,
  magnifyExpand: mdiMagnifyExpand,
  pencil: mdiPencil,
  thumbUp: mdiThumbUp,
  thumbDown: mdiThumbDown,
  trashCan: mdiTrashCan,
  arrowUpBoldCircle: mdiArrowUpBoldCircle,
  contentSave: mdiContentSave,
  shieldAccount: mdiShieldAccount,
  shieldLockOpen: mdiShieldLockOpen,
  informationBox: mdiInformationBox
};
