import type { ThemeDefinition } from "vuetify";

export const paletteGray = "#8d99ae";
export const paletteAntiFlashWhite = "#edf2f4";
export const palettePantoneRed = "#ef233c";
export const paletteFireEngineRed = "#d90429";
export const paletteDarkBg = "#2B2D42";

export const semanticSuccess = "#10B981";
export const semanticWarning = "#F59E0B";
export const semanticInfo = "#3B82F6";

export const darkThemeSurface = "#3A3D5A";

export const themes: Record<string, ThemeDefinition> = {
  light: {
    dark: false,
    colors: {
      primary: paletteFireEngineRed,
      "on-primary": "#FFFFFF",
      "primary-darken-1": "#b20321",
      secondary: paletteGray,
      "on-secondary": "#FFFFFF",
      "secondary-darken-1": "#727d8f",
      error: palettePantoneRed,
      "on-error": "#FFFFFF",
      "error-darken-1": "#D91E36",
      success: semanticSuccess,
      "on-success": "#FFFFFF",
      "success-darken-1": "#059669",
      warning: semanticWarning,
      "on-warning": "#FFFFFF",
      "warning-darken-1": "#D98C0A",
      info: semanticInfo,
      "on-info": "#FFFFFF",
      "info-darken-1": "#2563EB",
      background: paletteAntiFlashWhite,
      "on-background": paletteDarkBg,
      surface: "#FFFFFF",
      "on-surface": paletteDarkBg,
      "grey-50": "#F9FAFB",
      "grey-100": "#F3F4F6",
      "grey-200": "#E5E7EB",
      "grey-300": "#D1D5DB",
      "grey-400": "#9CA3AF",
      "grey-500": "#6B7280",
      "grey-600": "#4B5563",
      "grey-700": "#374151",
      "grey-800": "#1F2937",
      "grey-900": "#111827",
    },
    variables: {
      "border-color": paletteDarkBg,
      "border-opacity": 0.1,
      "high-emphasis-opacity": 1,
      "medium-emphasis-opacity": 0.75,
      "disabled-opacity": 0.5,
      "hover-opacity": 0.06,
      "focus-opacity": 0.1,
      "selected-opacity": 0.08,
      "activated-opacity": 0.16,
      "pressed-opacity": 0.14,
      "dragged-opacity": 0.1,
      "table-header-color": "#FFFFFF",
      "overlay-scrim-background": paletteDarkBg,
      "overlay-scrim-opacity": 0.5,
      "tooltip-background": paletteDarkBg,
      "shadow-key-umbra-color": paletteDarkBg,
    },
  },
  dark: {
    dark: true,
    colors: {
      primary: paletteGray,
      "on-primary": paletteDarkBg,
      "primary-darken-1": "#727d8f",
      secondary: paletteFireEngineRed,
      "on-secondary": "#FFFFFF",
      "secondary-darken-1": "#b20321",
      error: palettePantoneRed,
      "on-error": "#FFFFFF",
      "error-darken-1": "#D91E36",
      success: semanticSuccess,
      "on-success": "#FFFFFF",
      "success-darken-1": "#059669",
      warning: semanticWarning,
      "on-warning": "#FFFFFF",
      "warning-darken-1": "#D98C0A",
      info: semanticInfo,
      "on-info": "#FFFFFF",
      "info-darken-1": "#2563EB",
      background: paletteDarkBg,
      "on-background": paletteAntiFlashWhite,
      surface: darkThemeSurface,
      "on-surface": paletteAntiFlashWhite,
      "grey-50": "#1F2937",
      "grey-100": "#374151",
      "grey-200": "#4B5563",
      "grey-300": "#6B7280",
      "grey-400": "#9CA3AF",
      "grey-500": "#D1D5DB",
      "grey-600": "#E5E7EB",
      "grey-700": "#F3F4F6",
      "grey-800": "#F9FAFB",
      "grey-900": "#FFFFFF",
    },
    variables: {
      "border-color": paletteAntiFlashWhite,
      "border-opacity": 0.12,
      "high-emphasis-opacity": 0.9,
      "medium-emphasis-opacity": 0.7,
      "disabled-opacity": 0.5,
      "hover-opacity": 0.06,
      "focus-opacity": 0.1,
      "selected-opacity": 0.08,
      "activated-opacity": 0.16,
      "pressed-opacity": 0.14,
      "dragged-opacity": 0.1,
      "table-header-color": darkThemeSurface,
      "overlay-scrim-background": "#000000",
      "overlay-scrim-opacity": 0.6,
      "tooltip-background": paletteAntiFlashWhite,
      "shadow-key-umbra-color": "#000000",
    },
  },
};

export default themes;
