/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/layout/AppBar.vue')['default']
    AppDrawer: typeof import('./components/layout/AppDrawer.vue')['default']
    AppDrawerItem: typeof import('./components/layout/AppDrawerItem.vue')['default']
    AppFooter: typeof import('./components/layout/AppFooter.vue')['default']
    AppNotification: typeof import('./components/layout/AppNotification.vue')['default']
    AppNotificationItem: typeof import('./components/layout/AppNotificationItem.vue')['default']
    ButtonSettings: typeof import('./components/layout/ButtonSettings.vue')['default']
    DialogConfirm: typeof import('./components/DialogConfirm.vue')['default']
    IndexPage: typeof import('./components/IndexPage.vue')['default']
    StatsCard: typeof import('./components/StatsCard.vue')['default']
  }
}
