/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/admin/dashboard': RouteRecordInfo<'/admin/dashboard', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    '/admin/homepage': RouteRecordInfo<'/admin/homepage', '/admin/homepage', Record<never, never>, Record<never, never>>,
    '/admin/nested': RouteRecordInfo<'/admin/nested', '/admin/nested', Record<never, never>, Record<never, never>, '/admin/nested/' | '/admin/nested/menu1' | '/admin/nested/menu2' | '/admin/nested/menu2/' | '/admin/nested/menu2/menu2-1' | '/admin/nested/menu2/menu2-2'>,
    '/admin/nested/': RouteRecordInfo<'/admin/nested/', '/admin/nested', Record<never, never>, Record<never, never>>,
    '/admin/nested/menu1': RouteRecordInfo<'/admin/nested/menu1', '/admin/nested/menu1', Record<never, never>, Record<never, never>>,
    '/admin/nested/menu2': RouteRecordInfo<'/admin/nested/menu2', '/admin/nested/menu2', Record<never, never>, Record<never, never>, '/admin/nested/menu2/' | '/admin/nested/menu2/menu2-1' | '/admin/nested/menu2/menu2-2'>,
    '/admin/nested/menu2/': RouteRecordInfo<'/admin/nested/menu2/', '/admin/nested/menu2', Record<never, never>, Record<never, never>>,
    '/admin/nested/menu2/menu2-1': RouteRecordInfo<'/admin/nested/menu2/menu2-1', '/admin/nested/menu2/menu2-1', Record<never, never>, Record<never, never>>,
    '/admin/nested/menu2/menu2-2': RouteRecordInfo<'/admin/nested/menu2/menu2-2', '/admin/nested/menu2/menu2-2', Record<never, never>, Record<never, never>>,
    '/admin/table': RouteRecordInfo<'/admin/table', '/admin/table', Record<never, never>, Record<never, never>>,
    'Login': RouteRecordInfo<'Login', '/auth/login', Record<never, never>, Record<never, never>>,
  }
}
